In [2]:
import torch

In [3]:
x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])
print(x * y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([4,1])

In [5]:
x

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [6]:
x.shape

torch.Size([4, 1])

In [7]:
y = torch.rand([2,4])
y

tensor([[0.2714, 0.9313, 0.0240, 0.2116],
        [0.1655, 0.9792, 0.9580, 0.7606]])

In [8]:
# Flattening (Converting to 1 x n matrix).
y = y.view([1,8])

In [9]:
newList = [1,2,4]
newTensor = torch.Tensor(newList)
newTensor

tensor([1., 2., 4.])

In [16]:
fillTensor = torch.ones((4,))
fillTensor = fillTensor.new_full((3,4), 3.14)

In [18]:
addValue = fillTensor.add(1)
addValue

tensor([[4.1400, 4.1400, 4.1400, 4.1400],
        [4.1400, 4.1400, 4.1400, 4.1400],
        [4.1400, 4.1400, 4.1400, 4.1400]])